<?php
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Rocks\ReceiverTestData;

class ReceiverTestController extends Controller {

  public function view(ServerRequestInterface $request, ResponseInterface $response, $args) {
    session_setup();

    $num = $args['test'];

    if(!ReceiverTestData::exists($num)) {
      $response->getBody()->write('Test not found');
      return $response->withStatus(404);
    }

    $response->getBody()->write(view('receiver-test', [
      'title' => 'Webmention Rocks!',
      'num' => $num,
      'test' => ReceiverTestData::data($num),
      'published' => ReceiverTestData::published($num),
      'num_responses' => 0
    ]));
    return $response;
  }  

  public function start(ServerRequestInterface $request, ResponseInterface $response, $args) {
    session_setup();
    $params = $request->getQueryParams();
    
    $num = $args['test'];

    if(!ReceiverTestData::exists($num)) {
      $response->getBody()->write('Test not found');
      return $response->withStatus(404);
    }

    // Check that the URL entered is on the same domain as the user's website
    if(!domains_are_equal($_SESSION['me'], $params['url'])) {
      $_SESSION['error'] = 'host-mismatch';
      return $response->withHeader('Location', '/receive/'.$num)->withStatus(302);
    }

    // Store the URL and generate a hash for it
    $code = Rocks\Redis::generateCodeForTarget($params['url'], $num);

    return $response->withHeader('Location', '/receive/'.$num.'/'.$code);
  }

  public function process(ServerRequestInterface $request, ResponseInterface $response, $args) {
    session_setup();
    $params = $request->getQueryParams();
    
    $num = $args['test'];

    if(!ReceiverTestData::exists($num)) {
      $response->getBody()->write('Test not found');
      return $response->withStatus(404);
    }

    $code = $args['code'];

    if(!($data=Rocks\Redis::getTargetDataFromCode($code))) {
      $response->getBody()->write(view('receiver-test-not-found', [
        'title' => 'Webmention Rocks!',
        'error' => 'Not Found',
        'description' => 'This post was not found. The posts generated by this site are only valid for 48 hours and are automatically deleted after that time. You can start the test over.'
      ]));
      return $response;
    }

    $published = new DateTime($data->published);
    # TODO: Set the timezone to match the timezone of the post this links to
    $published->setTimeZone(new DateTimeZone('America/Los_Angeles'));



    $response->getBody()->write(view('receiver-test-run', [
      'title' => 'Webmention Rocks!',
      'num' => $num,
      'test' => ReceiverTestData::data($num),
      'published' => $published,
      'num_responses' => 0,
      'target' => $data->target
    ]));
  }

}
